const regionesComunas = {
    "Región Metropolitana de Santiago": [
        "Santiago", 
        "Cerrillos", 
        "Cerro Navia", 
        "Conchalí", 
        "El Bosque", 
        "Estación Central", 
        "Huechuraba", 
        "Independencia", 
        "La Cisterna", 
        "La Florida", 
        "La Granja", 
        "La Pintana", 
        "La Reina", 
        "Las Condes", 
        "Lo Barnechea", 
        "Lo Espejo", 
        "Lo Prado", 
        "Macul", 
        "Maipú", 
        "Ñuñoa", 
        "Pedro Aguirre Cerda", 
        "Peñalolén", 
        "Providencia", 
        "Pudahuel", 
        "Quilicura", 
        "Quinta Normal", 
        "Recoleta", 
        "Renca", 
        "San Joaquín", 
        "San Miguel", 
        "San Ramón", 
        "Vitacura", 
        "Puente Alto", 
        "Pirque", 
        "San José de Maipo", 
        "Colina", 
        "Lampa", 
        "Tiltil", 
        "San Bernardo", 
        "Buin", 
        "Calera de Tango", 
        "Paine", 
        "Melipilla", 
        "Alhué", 
        "Curacaví", 
        "María Pinto", 
        "San Pedro", 
        "Talagante", 
        "El Monte", 
        "Isla de Maipo", 
        "Padre Hurtado", 
        "Peñaflor"
    ],
    "Región de la Araucanía": [
        "Temuco", 
        "Carahue", 
        "Cholchol", 
        "Cunco", 
        "Curarrehue", 
        "Freire", 
        "Galvarino", 
        "Gorbea", 
        "Lautaro", 
        "Loncoche", 
        "Melipeuco", 
        "Nueva Imperial", 
        "Padre Las Casas", 
        "Perquenco", 
        "Pitrufquén", 
        "Pucón", 
        "Saavedra", 
        "Teodoro Schmidt", 
        "Toltén", 
        "Vilcún", 
        "Villarrica", 
        "Angol", 
        "Collipulli", 
        "Curacautín", 
        "Ercilla", 
        "Lonquimay", 
        "Los Sauces", 
        "Lumaco", 
        "Purén", 
        "Renaico", 
        "Traiguén", 
        "Victoria"
    ],
    "Región de Ñuble": [
        "Chillán", 
        "Bulnes", 
        "Chillán Viejo", 
        "Cobquecura", 
        "Coelemu", 
        "Coihueco", 
        "El Carmen", 
        "Ninhue", 
        "Ñiquén", 
        "Pemuco", 
        "Pinto", 
        "Portezuelo", 
        "Quillón", 
        "Quirihue", 
        "Ránquil", 
        "San Carlos", 
        "San Fabián", 
        "San Ignacio", 
        "San Nicolás", 
        "Treguaco", 
        "Yungay"
    ]
};